name: "ziweiShop"
mode: "dev"
version: "v1.0.0"
host: "127.0.0.1"
port: ":8080"
machine_id: 1
start_time: "2022-03-15"
oss_status: 0

log:
  level: "debug"
  filename: "ziweiShop.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  user: "root"
  password: "123456"
  port: "3306"
  dbname: "ziweiShop"
  max_open_conns: 200
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  password: "123456"
  port: "6379"
  db: 1
  pool_size: 100
